# Generated by Django 6.0.3 on 2026-04-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopToGrow', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopToGrow.category'),
        ),
    ]
